# yolov11_config.yaml
path: C:\Users\plaksych\PRP\dataset
train: train
val: val

# train:
#   # Path to training data
#   images: 'train/images'
#   labels: 'train/labels'

# validation:
#   # Path to validation data
#   images: 'val/images'
#   labels: 'val/labels'

# Model configuration
model: yolov11m.pt
  # architecture: 'yolov11'  # specify the YOLOv11 architecture
  # # input_size: [640, 640]    # input size of the model
  # num_classes: 3           # number of classes in your dataset
  # pretrained: true           # set to true to use pretrained weights
# Classes
nc: 3
names: 
  0: passport
  1: cover
  2: other

# Training hyperparameters
hyperparameters:
  epochs: 50                # number of training epochs
  batch_size: 16            # number of images per batch
  learning_rate: 0.001      # initial learning rate
  warmup_epochs: 3          # number of warmup epochs
  weight_decay: 0.0005      # weight decay for regularization
  lr_scheduler: true         # whether to use learning rate scheduler
  save_best_only: true      # save only the best model during training

# Augmentation settings
augmentation:
  random_flip: true         # whether to apply random horizontal flip
  random_scale: true        # whether to apply random scaling
  mosaic: true              # enable mosaic augmentation
  rotation: 30              # maximum rotation in degrees

# Logging and checkpointing
logging:
  save_dir: './logs'  # directory to save training logs
  checkpoint_dir: './checkpoints'  # directory to save model checkpoints